### ISSUE TITLE
Picom fails on multi monitor

### ISSUE THREAD

**Issue by ace-99** [Axarva/dotfiles-2.0#44] opened 2021-05-22 23:40 UTC
I run a laptop and dock it for a total of 3 monitors (including laptop).  Everything within these dotfiles works perfect when I use just the laptop... as soon as I xrandr to the dock and other monitors, seems like picom fails super hard. No transparency and opening a new terminal / the sidebar takes like 2 seconds and it is super choppy.  Anything I am doing wrong? Some helpful outputs below, **let me know** if anything else would be useful.

I just switched from qtile and all my hardware / docking / xrandr / picom was working there.  I did `picom &` from the `.xinitrc` in that config though, now it is commented out as xmonad does it.

Thanks in advance for anything!

#####  os
```bash
❯ uname -osr
Linux 5.12.5-arch1-1 GNU/Linux
```

##### gpu
```bash
❯ nvidia-smi
Sat May 22 19:33:19 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.31       Driver Version: 465.31       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   45C    P0    23W /  N/A |    126MiB /  5934MiB |     24%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     26838      G   /usr/lib/Xorg                     125MiB |
+-----------------------------------------------------------------------------+
```

##### xrandr command _(worked on qtile)_
```bash
eval "xrandr --output ${main} --primary --mode 2560x1440 --rate 144 --output ${second} --auto --rotate right --right-of ${main} --output eDP-1 --auto --left-of ${main} && setxkbmap -option caps:swapescape"
```

##### error
```bash
❯ picom -f &
[1] 42493

~
✦ ❯ [ 05/22/2021 19:35:00.802 x_fence_sync ERROR ] Failed to trigger the fence (X error 136 XSyncBadFence request 134 minor 15 serial 2208)
[ 05/22/2021 19:35:00.802 paint_all ERROR ] x_fence_sync failed, xrender-sync-fence will be disabled from now on.
x_set_picture_clip_region() has failed to allocate memory, at ../src/x.c:311. Aborting...

[1]  + abort (core dumped)  picom -f

```

**Comment by Axarva** [comment] 2021-05-23 03:02
I cannot test this config on multimonitor setups. However, if the issue is with picom, please use your older picom configs that used to work with qtile. Add in the class rules specified in the picom.conf in this repository and try commenting out blur.

**Comment by Axarva** [comment] 2021-05-23 07:25
I'm also curious what happens when you connect the monitors then restart picom...

**Comment by Kellegram** [comment] 2021-05-23 12:31
I have 2 monitors and have no such issues with the included picom config, this is likely due to the switch and killing picom then starting it when the switch is done will probably resolve it.

**Comment by ace-99** [comment] 2021-05-23 13:10
I tried a default config - receiving the same result, and tried commenting out blur - receiving the same result _(less blurring)_.  There is a specific fork of picom for this? Or is it just the config that is needed. I could be in conflict? 

```bash
~ took 10s
❯ paru -S picom
[sudo] password for user:
resolving dependencies...
looking for conflicting packages...
:: picom and picom-jonaburg-git are in conflict (compton). Remove picom-jonaburg-git? [y/N]
```

Here is me killing picom -> docking -> restarting -> same result
```bash
~
❮ ps -aux | grep picom
user       10549  1.7  0.3 585436 61288 ?        Ssl  08:57   0:00 picom -f
user       10980  0.0  0.0   6400  2328 pts/0    S+   08:57   0:00 grep --color=auto picom

~
❯ kill -12 10549

~
❯ screen-config -s dock

~
❯ ps -aux | grep picom
user       11148  0.0  0.0   6400  2380 pts/0    S+   08:57   0:00 grep --color=auto picom

~
❯ picom -f &
[1] 11176
[ 05/23/2021 08:57:48.987 parse_kawase_blur_strength INFO ] blur-strength: 6 [.iter = 3, .offset = 3.500000, .expand = 50]

~
✦ ❯ [ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_SGI_video_sync.
[ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_SGI_swap_control.
[ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_OML_sync_control.
[ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_MESA_swap_control.
[ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_EXT_swap_control.
[ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_EXT_texture_from_pixmap.
[ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_ARB_create_context.
[ 05/23/2021 08:57:49.121 glx_has_extension INFO ] Found GLX extension GLX_EXT_buffer_age.
[ 05/23/2021 08:57:49.147 gl_has_extension INFO ] Missing GL extension GL_GREMEDY_string_marker.
[ 05/23/2021 08:57:49.147 generate_dual_kawase_params INFO ] blur-strength: 6 [.iter = 3, .offset = 2.500000]
[ 05/23/2021 08:57:49.148 glGetUniformLocationChecked INFO ] Failed to get location of uniform 'opacity'. This is normal when using custom shaders.
[ 05/23/2021 08:57:49.177 x_fence_sync ERROR ] Failed to trigger the fence (X error 136 XSyncBadFence request 134 minor 15 serial 653)

```

I cannot really show the malfunction without taking a video.  When you open the dashboard _Win p_ all the little rectangles start up one by one taking about .5 seconds each.  They look like another already open tile (be it the web browser I am on or another terminal), then a bit later they all snap to the grey and show the correct icons and words.

**Comment by Kellegram** [comment] 2021-05-23 13:56
You need picom by jonaburg, main picom does not (yet) have certain things merged. That being said, nothing wrong with picom, you are getting fence errors, likely regarding Nvidia, Nvidia needs this set to true in picom: `xrender-sync-fence = true;`
That being said, no guarantees this will fix this specific issue. Also, the fork by jonaburg will likely not help here either, but it is needed in most configs. 

Also, axarva doesn't run picom with experimental backends, but it's actually required for some things in it to work. Run picom like so: `picom --experimental-backends &`

**Comment by ace-99** [comment] 2021-05-23 16:53
Tried both and still the same.  I appreciate the tips and info though. 

I wonder if it is something with the laptop having dedicated graphics and integrated. Has been the root of a couple past issues, it not knowing when to correctly use which one.  But I may just be grasping at nothing.

Will continue to poke around...

**Comment by Kellegram** [comment] 2021-05-23 20:47
Hmmm, system76-power can really help with hybrid graphics.

**Comment by Axarva** [comment] 2021-07-08 09:22
Since this isn't strictly an issue of this repository (seems more to do with nvidia drivers and stuff as suggested [here](https://superuser.com/questions/1601366/picom-failed-to-trigger-fence)), I'll be closing this for now.

**Closed by Axarva** 2021-07-08 09:22 UTC
Labels: bug
