### ISSUE TITLE
How do I make it properly work with dual monitors of different resolutions?

### ISSUE THREAD

**Issue by hamiecod** [Axarva/dotfiles-2.0#58] opened 2021-06-06 12:50 UTC
I have two monitors(Laptop screen & external monitor) of resolutions 1920x1080 and 1360x768 and the setup is very buggy.

**Comment by Axarva** [comment] 2021-06-07 12:39
Have you tried disabling picom?

**Comment by Kellegram** [comment] 2021-06-24 11:55
> Have you tried disabling picom?

Picom would have no impact in this scenario and XMonad offers some of the best multi-monitor experience on linux. I would imagine it's eww and such that are what he considers "buggy"? Also, on WMs it's up to individual user to deal with graphics settings, so he might need to mess with xrandr, nvidia-settings or w/e else he should use.

**Comment by hamiecod** [comment] 2021-06-24 12:15
Sorry for not replying earlier, I was just a little busy.

So I tried disabling picom, but it didn't give me the desired experience. I guess it is because the config is currently not compatible with dual monitors of **different resolutions**.

I tried different xrandr configs and just made my experience better with the config by scaling my low res. monitor, it was a lot better but certainly not the best.

**Comment by Kellegram** [comment] 2021-06-24 14:34
In general Linux desktop has a lot of problems with both HiDPi and multi-res setups. Always had them and will continue having them for many years forward, while the problem could be related to configs here, it could also just be that you are missing something on arch/gentoo that other distros already do for you (assuming you had better experience on other distros or DEs (which also do a lot of work for you)). Hard to say, would have to see your setup, including your xrandr setup and w/e else you have for your GPU. I would double check that you have the required drivers. You will need ``nvidia`` or if you have a newer Nvidia card or a diff nvidia driver if your card is a bit older. You will need something for AMD too, the installer has some random drivers it asks you about but the list is not complete.

**Comment by hamiecod** [comment] 2021-06-24 16:11
My multi-res setup never worked good on linux distros, though it works the best on Windows 10. 
I have an integrated intel gpu so i have mesa installed
for my xrandr config it is just this:
`xrandr --output HDMI1 --right-of eDP1 --scale 1.31`
scaled it to get a better window shift between my monitors

**Comment by hamiecod** [comment] 2021-07-05 14:23
Should we close this issue?

**Comment by Axarva** [comment] 2021-07-06 03:09
Sure, if the issue was resolved

**Comment by hamiecod** [comment] 2021-07-06 03:15
The issue wasn't resolved directly, by changing the config, but I adapted my monitor configuration to the configuration by changing the scaling.

**Comment by Axarva** [comment] 2021-07-06 03:53
Well, if the issue is resolved, could you specify the exact steps you took? Then we may close this issue.

**Comment by Axarva** [comment] 2021-07-21 06:12
Closing.

**Closed by Axarva** 2021-07-21 06:12 UTC
Labels: question
