### ISSUE TITLE
Bars don’t show up or anything (panellauncher)

### ISSUE THREAD

**Issue by bloky246** [Axarva/dotfiles-2.0#147] opened 2022-05-28 04:17 UTC
**Describe the bug**
Bottom and top panel launcher doesn’t show

**To Reproduce**
Install the Environment as normal

**Expected behavior**
Panel launcher to work and appear

**Screenshots**
![image](https://user-images.githubusercontent.com/25247083/170809472-65ed167b-c2bb-4443-ada1-1f2a10d277c6.jpg)

**Desktop (please complete the following information):**
 - OS: [Arch Linux]

**Additional context**
If anyone can help please do so (:

**Comment by RoundTable99** [comment] 2022-05-29 19:31
I've got the same issue, but the side bars show up and stuff. Is it the same for you? @bloky246

**Comment by ArmoredVortex** [comment] 2022-05-30 07:53
#145 Duplicate?

**Comment by RoundTable99** [comment] 2022-05-30 11:05
Didn't know there was a thread open already, but it helped fix things for meOn 30 May 2022 08:53, Rachit Kumar Pandey ***@***.***> wrote:
#145 Duplicate?

**Comment by digvj1** [comment] 2022-06-04 13:02
> 
I'm still facing the issue. Can you elaborate on what to do. Do I have to edit the Bartoggle script and change bin/tint2 with sbin/tint2 (with some texteditor) or something else.

**Comment by RoundTable99** [comment] 2022-06-04 14:20
yes. you need to edit the bartoggle script with sbin instead of bin

**Comment by bloky246** [comment] 2022-06-05 21:54
> I've got the same issue, but the side bars show up and stuff. Is it the same for you? @bloky246


Yea

**Comment by gatoroto** [comment] 2022-06-14 18:02
I've got the same problem on fresh Arch install, but installing tint2 from AUR didn't help. :(

**Comment by ArmoredVortex** [comment] 2022-06-15 06:07
> I've got the same problem on fresh Arch install, but installing tint2 from AUR didn't help. :(

Did you change the contents of the `~/bin/bartoggle` script ?

**Comment by gatoroto** [comment] 2022-06-15 06:08
> > I've got the same problem on fresh Arch install, but installing tint2 from AUR didn't help. :(
> 
> Did you change the contents of the `~/bin/bartoggle` script ?

Yep, changed paths to /sbin/tint2

**Comment by ArmoredVortex** [comment] 2022-06-15 06:12
Can you try running the `~/bin/bartoggle` script manually in the terminal. The output messages might be helpful.

**Comment by somedayitwillend** [comment] 2022-06-21 10:16
> **Describe the bug** Bottom and top panel launcher doesn’t show
> 
> **To Reproduce** Steps to reproduce the behavior: Install the Environment as normal
> 
> **Expected behavior** Panel launcher to work and appear
> 
> **Screenshots** ![image](https://github.com/assets/25247083/65ed167b-c2bb-4443-ada1-1f2a10d277c6)
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Arch Linux]
> 
> **Additional context** If anyone can help please do so (:

I have the same issue could someone please help me out? *-*

**Comment by Axarva** [comment] 2022-06-27 11:33
Assuming this is either a duplicate of #145 or #153, I believe this can be closed. In the case the issue still persists, please comment and the issue will be reopened. Also, thanks to everyone who helped the issue creator!

**Closed by Axarva** 2022-06-27 11:33 UTC
