### ISSUE TITLE
Having issues logging out and shutting down

### ISSUE THREAD

**Issue by slink007** [Axarva/dotfiles-2.0#68] opened 2021-07-02 15:54 UTC
If I open up the sidebar and attempt to shutdown or log out from there I will get the prompt but nothing happens once I've entered my reply.  I've tried "y" and "yes" and anything else that would make sense.  I absolutely cannot shutdown with that method.

If I use the Super + Shift + Q combination I get the bar which tells me goodbye and which has several icons beneath it.  If I click the icon for power I see nothing happen.  However, I find that if I then switch to screen 2 the prompt dialog is shown there.  Once I have it visible I can enter my reply and the system shuts down.  Same thing with logging out.  I can click the icon, nothing happens, I go to the next screen and proceed from there.  So at least this works but it is a bit unusual.

Any ideas what I could check or adjust to make this function a bit more normally?

**Comment by Axarva** [comment] 2021-07-03 05:21
The scripts. Check the scripts in question. They are in ~/bin as powermenu.sh and in ~/.config/eww/scripts/.

**Comment by Esgodra** [comment] 2021-07-14 01:51
I tested the scripts by calling them directly from the console, just as it is done from the .xml and they work as expected, but when calling them from the buttons that invoke them, they stop working correctly, I keep trying to fix it

**Comment by Axarva** [comment] 2021-07-14 04:26
Well, this is an eww issue. I’ll notify the devs and probably fiddle around with eww source code myself to see if I can fix it. For all I know, it could be a feature, not a bug by limiting eww’s privileges.

**Comment by Esgodra** [comment] 2021-07-14 18:29
Ok, the mod + shift + q menu, works with double click on the option or with enter, thanks for your help and this amazing customization @Axarva , I will check the permissions of eww, anyway, this issue and that is very good for me

**Comment by Axarva** [comment] 2021-07-19 13:11
Alright, will be closing for now, since this is more of an eww issue.

**Closed by Axarva** 2021-07-19 13:11 UTC
