### ISSUE TITLE
I can't install on a fresh arch linux installation

### ISSUE THREAD

**Issue by blackbirdsr71** [Axarva/dotfiles-2.0#73] opened 2021-07-18 03:44 UTC
Hi all,
I followed the installtion as described in SavvyNik's video issuing the install-on-arch.sh script. Before that, i installed the suggested dependencies. Everything seems to go fine until i am asked to choose my screen resolution. After selecting the first option i end directly to the notes at the final of the procedure as if the installation was complete. Here is an image, since i haven't the system configured so in order to paste the code decently: 

![WhatsApp Image 2021-07-18 at 00 04 20_mk2](https://user-images.githubusercontent.com/10891113/126102495-8de45d8b-cf87-453c-9655-10adc54cc115.jpeg)

Is it possible that the issue is related to a mistake installing EWW or Tint2-1?

I was afraid that the problem could be an xmonad compiling issue, but i tested a basic installtion and it works fine. Any clue what's happening? Thanks!

**Comment by Axarva** [comment] 2021-07-18 04:13
It seems it is installing correctly. Try launching xmonad through startx.

**Comment by Shahab96** [comment] 2021-07-18 19:49
You need to have an xorg server set up in order to use this, since xmonad is just the window manager. Try installing one and coming back. 

This issue might also be a duplicate of #72  @Axarva #

**Comment by blackbirdsr71** [comment] 2021-07-18 19:55
Thanks to both i will give it a try and then i wiil tell what happened.

**Comment by Axarva** [comment] 2021-07-19 13:10
> You need to have an xorg server set up in order to use this, since xmonad is just the window manager. Try installing one and coming back.
> 
> This issue might also be a duplicate of #72 @Axarva

Could be. Most likely is, although there's the added issue of executing the script as root. *I hate it when people do that.*

**Comment by blackbirdsr71** [comment] 2021-07-19 13:55
> > You need to have an xorg server set up in order to use this, since xmonad is just the window manager. Try installing one and coming back.
> > This issue might also be a duplicate of #72 @Axarva
> 
> Could be. Most likely is, although there's the added issue of executing the script as root. _I hate it when people do that._

It's not my case!

**Comment by Axarva** [comment] 2021-07-19 15:48
True, that's #72 :)

**Comment by blackbirdsr71** [comment] 2021-07-20 07:06
Hi Axarva,
Finally it worked!!! Thanks!

**Comment by Axarva** [comment] 2021-07-20 07:11
Well then, I’ll close this.

**Closed by Axarva** 2021-07-20 07:11 UTC
Labels: question
