### ISSUE TITLE
Tint2 panel overlapping

### ISSUE THREAD

**Issue by h4r1337** [Axarva/dotfiles-2.0#166] opened 2022-09-01 14:09 UTC
The tint2 top right panels are overlapping and stacked together(see screenshot):
![image](https://user-images.githubusercontent.com/72344536/187934391-d0a2bc36-7f0b-44ea-b431-07c16726fba3.png)

**Desktop :**
 - OS: Pop OS 22.04
 - WM: XMonad
 - DE: Gnome

**Comment by h4r1337** [comment] 2022-09-02 04:26
I can fix this by adjusting the panel margin, but not sure why this issue is formed in the first place.

**Comment by Axarva** [comment] 2022-09-02 10:37
Yes, this happens when the resolution of your desktop doesn't match one of the resolutions specified in the install script. For now, the fix is to just adjust the panel margin with tint2conf, I'm sorry for the inconvenience.


This is a duplicate of #82, so I'll close this for now.

**Closed by Axarva** 2022-09-02 10:37 UTC
