### ISSUE TITLE
Eww getweather

### ISSUE THREAD

**Issue by morenoled** [Axarva/dotfiles-2.0#14] opened 2021-02-07 23:03 UTC
The weather only shows up if I run "exec ~/.config/eww/scripts/getweather" and then "eww kill && eww daemon"
How can I get it running since the beginning?
And yes, I edited may crontab, as you show in the tutorial.
Everything thing else is running fine. By the way, I loved this xMonad theme you made. Thanks for that.

**Comment by morenoled** [comment] 2021-02-08 00:05
![a](https://user-images.githubusercontent.com/78452560/107163390-f7926500-6987-11eb-9ed2-ed13da555f4f.jpg)

I forgot something, this folders links, they don`t open the respective directory. It`s a problem or not? This only show the home folders and do nothing?
Tks

**Comment by morenoled** [comment] 2021-02-08 00:45
![b](https://user-images.githubusercontent.com/78452560/107164378-8c4b9180-698d-11eb-87cd-75589a7a9452.jpg)
another thing. my wi-fi connection don't show on the up tray bar. only pop-up "Connected to". not the network manager

**Comment by Axarva** [comment] 2021-02-08 05:42
Hey there


You need to put modify your crontab to execute the weather scripts properly, otherwise, it only works when you execute the script manually. For more info on crontab, I suggest you look at the `cron` daemon. [A handy reference is here.](https://www.redhat.com/sysadmin/automate-linux-tasks-cron)

To open those directories you need the thunar file manager, but you can modify the `~/.config/eww/eww.xml` file to launch another file manager instead. 

Finally, for that bar, that is NOT the nm-applet (I am not a fan of systrays). That is a custom script. You could make it launch `nmtui` in your preferred terminal instead, which can be done by using the `tint2conf` utility. Otherwise, it will only give you info on whether you are connected to a network or not.

Hope this helps!

**Comment by morenoled** [comment] 2021-02-08 12:29
Let's begin
I fixed the thunar to nautilus.
the crontab either.
about the nmcli, let me see if I got it. this script is only to show if I connect or not? So, that's not wrong with it?
I use Linux since the end of 2000 (Conectiva Linux, later integrated with Mandrake, making Mandriva), but my last jobs made me use Windows for a long time, so I forgot some simple stuffs. One is how to call nmtui from there in my terminal (just like you, I use alacritty). I now, it's a noobie question, sorry for that, but my memory sucks, and for o noobie, I'm very glade to make a Arch Linux  install and cloned you xmonad. but this simple stuffs I can't really remember. I know I can open a terminal and set it up by my self, but learn how to make this with one click will make me very glad. 
PS: Man, how I loved you xmonad. It's one of the most beautiful and simple to use I ever saw. I will use it for a very long time before adventure for another one. I get everything I need here, in a simple way. thanks for your efforts

**Comment by Axarva** [comment] 2021-02-08 13:36
![image](https://user-images.githubusercontent.com/66304313/107226668-82d03100-6a42-11eb-9ed7-40bb2403ae0e.png)
In here if you edit this specific line:
![image](https://user-images.githubusercontent.com/66304313/107226757-9f6c6900-6a42-11eb-9e28-ee738681fc5e.png)

To read this:
![image](https://user-images.githubusercontent.com/66304313/107226796-ac895800-6a42-11eb-8810-82fd61ec8c18.png)

And then apply the changes, it should work!
(The command is `alacritty -e nmtui` in case I oversimplified things.)
And I very much appreciate your kind words! Thank you!

**Comment by Axarva** [comment] 2021-02-10 04:02
I’ll be closing this assuming everything worked.
If something doesn’t work feel free to comment and the issue will be reopened :)

**Comment by morenoled** [comment] 2021-02-10 05:37
sorry for take too long to answer. I had a busy day today, its 2am and I`m finally free now.
Everything works fine now, but sometimes the "getweather" don't work. Even when I run "exec ~/.config/eww/scripts/getweather" and then "eww kill && eww daemon". Is this a bug?
And now another thing is happening. When I click on the links (like bin) in the "centerlaunch"
![center](https://user-images.githubusercontent.com/78452560/107467854-b3e55a00-6b45-11eb-9a3b-54f4e87dfcbf.jpg)

.

this shows up

.
 
![erronautilus](https://user-images.githubusercontent.com/78452560/107467899-c5c6fd00-6b45-11eb-8443-b9a24f776911.jpg)
(translation) "Ops! Something got wrong. 
It's not possible to find the requested file. check the spelling and try again"
Some links, like "Documentos" (Documents) works fine, but some don't.

And something I forgot to say before, I installed "cronie", from pacman, but when I run "systemctl status cron" this shows up "Unit cron.service could not be found.", but when I change to "... cronie" this shows up 
![cronieenable](https://user-images.githubusercontent.com/78452560/107469144-fa3bb880-6b47-11eb-873c-5fab386f06ab.jpg)

It's working fine, right? Do the same thing as cron do.

And finally, LOL, can't I automatically save a screenshot in a file/folder? I'm bypassing using "Pinta". Works fine, but if I can make it happen auto, it's a lot better.

Again, thanks for you time and help. I'm sorry for bothering you, but I really whant to use your mod. I'm very happy with it.

**Comment by Axarva** [comment] 2021-02-10 05:45
The document not opening through centerlaunch is probably because of a minor bug. The cron service looks great, and as for saving a screenshot, “Mod + Print” will save the screenshot you take into ~/Documents. 

The cron daemon executes the script always at the 30th minute of every hour. So it could sometimes not show up, but it will show up soon enough. If you are impatient you could execute the script manually. If the script doesn’t still work fine, please check your network connection, that could probably be the cause.

**Comment by morenoled** [comment] 2021-02-10 13:15
I don't know it's because my system is in Brazilian Portuguese, but the "mod+print" don't anything there.

And the getweather is back thanks again. =]

**Comment by Axarva** [comment] 2021-02-11 07:24
`Mod + Print` should allow you to screenshot your screen, then save the file to your `~/Desktop`.
What happens when you hit the `Print` key? Is it `flameshot` being launched or `maim`?

**Comment by morenoled** [comment] 2021-02-12 00:22
its been **maim** before, but now I installed **flameshot** and configured it on **xmonad.hs**. I putted the path to go, and now it's working. Thanks again my friend, for everything. I hope you have a nice 2021. Be safe.

**Comment by morenoled** [comment] 2021-02-12 00:28
its been **maim** before, but now I installed **flameshot** and configured it on **xmonad.hs**. I putted the path to go, and now it's working. 
But something I searched on the entire Google and did not find is how to activate de touchpad touch (to make the touch as a click), instead of clicking down. I can make it happen on Gnome, but not in xmonad.
Thanks again my friend, for everything. I hope you have a nice 2021. Be safe.

**Comment by morenoled** [comment] 2021-02-12 00:28
its been maim before, but now I installed flameshot and configured it on xmonad.hs. I putted the path to go, and now it's working.
But something I searched on the entire Google and did not find is how to activate de touchpad touch (to make the touch as a click), instead of clicking down. I can make it happen on Gnome, but not in xmonad.
Thanks again my friend, for everything. I hope you have a nice 2021. Be safe.

**Comment by Axarva** [comment] 2021-02-12 02:51
Ah, I hope you get flameshot working, because I couldn’t, and therefore settled on maim as you can see in #2.

As for getting your touchpad to work, you need to configure it through Xorg. [This here should help, I use it myself.](https://howchoo.com/linux/the-perfect-almost-touchpad-settings-on-linux-2)

**Comment by morenoled** [comment] 2021-02-12 06:56
I used this **"flameshot full -p /home/path/to/directory"** on xmonad.hs, and worked fine to me.
And about the **mtrack**, when I installed it to my notebook, my touchpad stopped work, so I had to reinstall **xf86-input-synaptics** to get it back.

**Comment by Axarva** [comment] 2021-02-12 07:03
Ah, that's great! Maybe this will help:

![image](https://user-images.githubusercontent.com/66304313/107739151-59f4b800-6d30-11eb-8f1c-caee9e7c7839.png)
Could you try adding the following lines to `/etc/X11/xorg.conf.d/90-touchpad.conf` (create the file if it's not there)?

```
Section "InputClass"
       	Identifier "touchpad"
       	MatchIsTouchpad "on"
       	Driver "libinput"
       	Option "Tapping" "on"
       	Option "TappingButtonMap" "lrm"
       	Option "NaturalScrolling" "on"
       	Option "ScrollMethod" "twofinger"
EndSection
```
Try re-logging into xmonad and see if it works for you. You might need to change the driver entry to the specific driver of your touchpad.

**Comment by morenoled** [comment] 2021-02-12 07:18
"It's alive!!! It's alive!!!"
Thank you so much my friend. Now it's running perfectly.
I think we can finally close this topic. : )
I appreciate your attention and again, have a nice 2021. Be safe.

**Comment by Axarva** [comment] 2021-02-12 07:20
Alright, glad it all worked out. Same to you sir, have a great year and be safe, and thank you for trying this out!

**Closed by Axarva** 2021-02-12 07:20 UTC

**Comment by morenoled** [comment] 2021-02-26 01:40
I found the what was happening. My system is in Brazilian Portuguese, I just translated the `| grep "connected to"`in the `x` part and the yes in the `y` part. Simple as possible.
Sorry for the trouble, and thanks again.


> Opening up `tint2conf` from the terminal or the application launcher and then editing the `customscripts.tint2rc` file will show the following window:
> ![image](https://user-images.githubusercontent.com/66304313/107226668-82d03100-6a42-11eb-9ed7-40bb2403ae0e.png)
> In here if you edit this specific line:
> ![image](https://user-images.githubusercontent.com/66304313/107226757-9f6c6900-6a42-11eb-9e28-ee738681fc5e.png)
> 
> To read this:
> ![image](https://user-images.githubusercontent.com/66304313/107226796-ac895800-6a42-11eb-8810-82fd61ec8c18.png)
> 
> And then apply the changes, it should work!
> (The command is `alacritty -e nmtui` in case I oversimplified things.)
> 
> You could also do this by editing the file itself as well, but instead of searching for the specific line, I find this quicker.
> And I very much appreciate your kind words! Thank you!
