### ISSUE TITLE
1080p resolution option not scaled properly

### ISSUE THREAD

**Issue by abhivemp** [Axarva/dotfiles-2.0#111] opened 2021-10-13 23:24 UTC
**Describe the bug**
Hey everyone! I installed arch and installed this beautiful theme and I am loving it so far! Thank you so much @Axarva !
I am wondering why my current setup (i.e. after running the arch setup script and rebooting), I get a different resolution with the panels, widgets unevenly spaced? 

I run a 1080p monitor for my CPU and after running the script the resolution seemed off, I ran these commands (`xdpyinfo | grep 'dimensions:'`) and found out the resolution it was set to 3840x2160 and this is how it looks like:

I thought this was a mistake on my side so after running `xrandr -s 1920x1080`, this is how my screen looks like:

![image](https://user-images.githubusercontent.com/35072868/137253622-077e043f-4edd-49db-aa0c-e7e53702bf9d.png)

Would love to know if there is a way to fix this and if I am doing anything wrong with the setup. 

I have also seen these issues also regarding the rounded edges, and scaling: #35 #17
Thanks!! 

**Desktop (please complete the following information):**
 - OS: Arch

**Comment by abhivemp** [comment] 2021-10-14 04:54
I realized I didn't add screenshots so I've added them.

**Comment by Axarva** [comment] 2021-11-04 12:53
Hm, seems like picom isn’t working, and the bars on the top right are overlapped. Try shortening and repositioning the bars with tint2conf. I’ll fix all scaling issues as soon as I can.

**Comment by Axarva** [comment] 2022-01-20 16:50
Since this is technically a duplicate of #82, I'll be closing this for now. If you need more support, please comment on this again and I'll be happy to help :) 
And yes, I've started working on making the setup usable on different resolutions.

**Closed by Axarva** 2022-01-20 16:50 UTC
