### ISSUE TITLE
High CPU usage with bars enabled

### ISSUE THREAD

**Issue by tlavoie** [Axarva/dotfiles-2.0#20] opened 2021-02-24 21:03 UTC
**Describe the bug**
I've gone through the basic configuration, looks beautiful. Thanks!
However, I have noticed that tint2 is pegging one CPU core whenever the main bars are enabled. 
The process identified in htop shows that it is tint2 running the customscripts.tint2rc config file.

**To Reproduce**
1. Start my desktop
2. Open a terminal, such as alacritty
3. Open htop
4. Toggle Mod+b to see the CPU usage drop when the bars are disabled

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: EndeavourOS (Arch-based)
 - Browser: none
 - Version Current from git

**Additional context**

**Comment by morenoled** [comment] 2021-02-25 02:45
I checked this is my notebook and happens with me too.
Thanks for show me this... I imagined it's because my computer laziness. Now I just close the bars and it's running better. =]

**Comment by tlavoie** [comment] 2021-02-25 03:19
Good, I'm not seeing things.  ;)

I have narrowed it down a bit further, so it is specific to the Panel section in that config file. If it's uncommented and the bars are open, CPU is cranking. I may fiddle a bit further to see if there's a specific setting, as I don't know well what they do.

**Comment by tlavoie** [comment] 2021-02-25 04:51
Little farther along. Having any of the "executor" sections in panel_items does this. Guessing there is weird behavior in tint2 for executors, which appear to be recent. Not all samples online do this, but some (like all of these) do.

**Comment by morenoled** [comment] 2021-02-26 02:50
If you have any solution, please post it, if you can. I tried some changes here, and one of my CPU still at 100%.
thanks again.

**Comment by Axarva** [comment] 2021-02-26 11:37
Hmm, this seems weird. I have had no issues whatsoever on my machine, so I can't specifically tell what this is about. The CPU usage should be limited until and unless your executors are running on very quick intervals such as a single second, so I advise you to check that. That shouldn't be the case though, since my configurations set the timings to quite reasonable gaps, but that may still be the key to solving the problem. Good luck!

**Comment by greenbourne277** [comment] 2021-04-13 18:28
I'm facing the same CPU issue. @Axarva could you elaborate where the intervals can be changed? Thanks in advance :)

**Comment by greenbourne277** [comment] 2021-04-15 07:46
Ok the problem has been solved. With glibc-2.33 a wrong computed timer is the cause of the issue. For more detailed information see https://gitlab.com/o9000/tint2/-/issues/800
The fix is not in the arch repo yet but should be soon very soon according to one of the maintainers. My suggestion would be to pull the change by yourself for now and build it.

Best, 
Christian

FYI @tlavoie  @morenoled

**Comment by tlavoie** [comment] 2021-04-15 15:30
Awesome, thanks!

**Comment by Axarva** [comment] 2021-04-23 15:18
> Ok the problem has been solved. With glibc-2.33 a wrong computed timer is the cause of the issue. For more detailed information see https://gitlab.com/o9000/tint2/-/issues/800
> The fix is not in the arch repo yet but should be soon very soon according to one of the maintainers. My suggestion would be to pull the change by yourself for now and build it.
> 
> Best,
> Christian
> 
> FYI @tlavoie @morenoled

Thank you so much! This issue had left me baffled too, and I haven't had the time to properly investigate.
I believe it's time we closed this issue.
Thank you so much!

**Closed by Axarva** 2021-04-23 15:18 UTC
Labels: bug

**Comment by Axarva** [comment] 2021-06-24 09:02
This has now been finished completely. I have included a newer binary in 212fa2c that fixes this issue.
